/*
 * This source file was generated by the Gradle 'init' task
 */

package dev.danielblasina;

import dev.danielblasina.config.DBConfig;
import dev.danielblasina.config.parsers.YamlParser;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws SQLException, IOException, URISyntaxException {
        var nRecords = Integer.parseInt(args[0]);
        var dbConfig = DBConfig.parseFrom(new YamlParser());
        var table = new Table(dbConfig, "products");
        table.create();
        table.populate(nRecords);
    }
}
