/*
 * This source file was generated by the Gradle 'init' task
 */

package dev.danielblasina;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.stream.IntStream;

public class App {
    public static void main(String[] args) throws SQLException {
        var nRecords = Integer.parseInt(args[0]);
        var connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "password");

        connection.createStatement().executeUpdate("DROP TABLE IF EXISTS products");
        connection.createStatement().executeUpdate(
            "CREATE TABLE products (\n" + "  product_id int(11) NOT NULL AUTO_INCREMENT,\n"
                + "  product_name varchar(150) NOT NULL,\n"
                + "  PRIMARY KEY (`product_id`)\n"
                + ");");

        var range = IntStream.range(0, nRecords).iterator();
        while (range.next() != 0) {
            connection.createStatement()
                .executeUpdate("INSERT INTO products(product_name) VALUES('afsdfdf')");
        }
    }
}
